version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mini-paas-postgres
    environment:
      POSTGRES_DB: mini_paas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini_paas"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  