server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "minipaas"
  sslmode: "disable"

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  expires_in: 24

kubernetes:
  config_path: ""
  namespace: "default"

docker:
  registry_url: "docker.io"
  registry_user: ""
  registry_password: "" 